#!/usr/bin/env bash
# Install daytrader-bot as a systemd service on Linux.
#
# Run from the repo root after clone + venv + .env are ready:
#   chmod +x deploy/install-linux-systemd.sh
#   ./deploy/install-linux-systemd.sh
#
# Options (env vars):
#   INSTALL_DIR  — project path (default: directory containing this script's parent)
#   RUN_USER     — unix user for the service (default: current user, not root)
#   SERVICE_NAME — systemd unit name (default: daytrader)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${INSTALL_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
RUN_USER="${RUN_USER:-$(id -un)}"
SERVICE_NAME="${SERVICE_NAME:-daytrader}"
UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
VENV_PYTHON="${INSTALL_DIR}/.venv/bin/python"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Re-run with sudo so the unit can be installed under /etc/systemd/system:"
  echo "  sudo INSTALL_DIR=\"$INSTALL_DIR\" RUN_USER=\"$RUN_USER\" $0"
  exit 1
fi

if [[ ! -x "$VENV_PYTHON" ]]; then
  echo "ERROR: venv not found at ${VENV_PYTHON}"
  echo "Create it first:"
  echo "  cd \"$INSTALL_DIR\""
  echo "  python3 -m venv .venv && .venv/bin/pip install -r requirements.txt && .venv/bin/pip install -e ."
  exit 1
fi

if [[ ! -f "${INSTALL_DIR}/.env" ]]; then
  echo "WARNING: ${INSTALL_DIR}/.env missing — copy .env.example and fill in keys before trading."
fi

if ! id "$RUN_USER" &>/dev/null; then
  echo "ERROR: user '$RUN_USER' does not exist."
  exit 1
fi

mkdir -p "${INSTALL_DIR}/data" "${INSTALL_DIR}/logs"
chown -R "${RUN_USER}:${RUN_USER}" "${INSTALL_DIR}/data" "${INSTALL_DIR}/logs"
if [[ -f "${INSTALL_DIR}/.env" ]]; then
  chown "${RUN_USER}:${RUN_USER}" "${INSTALL_DIR}/.env"
  chmod 600 "${INSTALL_DIR}/.env"
fi

cat >"$UNIT_PATH" <<EOF
# Generated by deploy/install-linux-systemd.sh — edit and re-run the script to update.

[Unit]
Description=daytrader-bot intraday trading service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${RUN_USER}
Group=${RUN_USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=${VENV_PYTHON} ${INSTALL_DIR}/main.py
Restart=on-failure
RestartSec=10
EnvironmentFile=-${INSTALL_DIR}/.env
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

echo "Installed ${UNIT_PATH}"
echo "  User:      ${RUN_USER}"
echo "  Directory: ${INSTALL_DIR}"

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}.service"

if [[ -f "${INSTALL_DIR}/.env" ]]; then
  systemctl restart "${SERVICE_NAME}.service"
  echo ""
  echo "Service started. Status:"
  systemctl --no-pager status "${SERVICE_NAME}.service" || true
  echo ""
  echo "Follow logs:  journalctl -u ${SERVICE_NAME} -f"
else
  systemctl start "${SERVICE_NAME}.service" || true
  echo ""
  echo "Unit enabled but NOT started (no .env). After creating .env:"
  echo "  sudo systemctl start ${SERVICE_NAME}"
fi
